sudo: required

launguage: java

notifications:
  slack: b-side7:ptNI2JvkjXHWp5wEQfEse9pe

services:
  - docker
  
branches:
  only:
  - develop
  - master
  # - production

jobs:
  include:
    - stage: build
      script: 
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip -qq awscliv2.zip
        - sudo ./aws/install
        - docker build -t $APP_IMAGE:$(echo $TRAVIS_BRANCH | tr / -)-$TRAVIS_BUILD_NUMBER -f ./front/Dockerfile .
        - chmod +x ./scripts/push-app-image.sh
        - ./scripts/push-app-image.sh
    - script: 
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip -qq awscliv2.zip
        - sudo ./aws/install
        - docker build -t $SERVER_IMAGE:$(echo $TRAVIS_BRANCH | tr / -)-$TRAVIS_BUILD_NUMBER -f ./server/Dockerfile .
        - chmod +x ./scripts/push-server-image.sh
        - ./scripts/push-server-image.sh
    - stage: deploy
      deploy:
        - provider: codedeploy
          revision_type: github
          application: block-server-dev
          deployment_group: block-server-deploy-group-dev
          region: ap-northeast-2
          wait-until-deployed: true
          on:
            branch: 
              develop
        # - provider: codedeploy
        #   revision_type: github
        #   application: block-server-staging
        #   deployment_group: block-server-deploy-group-staging
        #   region: ap-northeast-2
        #   wait-until-deployed: true
        #   on:
        #     branch: 
        #       master
        # - provider: codedeploy
        #   revision_type: github
        #   application: block-app-dev
        #   deployment_group: block-app-deploy-group-dev
        #   region: ap-northeast-2
        #   wait-until-deployed: true
        #   on:
        #     branch: 
        #       develop
        # - provider: codedeploy
        #   revision_type: github
        #   application: block-app-staging
        #   deployment_group: block-app-deploy-group-staging
        #   region: ap-northeast-2
        #   wait-until-deployed: true
        #   on:
        #     branch: 
        #       master
