// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.block.server._generated.proto.hello;

public final class Helloworld {
  private Helloworld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultiplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultiplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\"\034\n\014HelloRequest\022\014\n\004na" +
      "me\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t\"" +
      ",\n\nAddRequest\022\016\n\006numOne\030\001 \001(\005\022\016\n\006numTwo\030" +
      "\002 \001(\005\"\032\n\010AddReply\022\016\n\006result\030\001 \001(\005\"1\n\017Mul" +
      "tiplyRequest\022\016\n\006numOne\030\001 \001(\005\022\016\n\006numTwo\030\002" +
      " \001(\005\"\"\n\020MultiplyResponse\022\016\n\006result\030\001 \001(\005" +
      "2\220\001\n\007Greeter\022(\n\010SayHello\022\r.HelloRequest\032" +
      "\013.HelloReply\"\000\022(\n\014AddTwoNumber\022\013.AddRequ" +
      "est\032\t.AddReply\"\000\0221\n\010Multiply\022\020.MultiplyR" +
      "equest\032\021.MultiplyResponse\"\000B+\n\'com.block" +
      ".server._generated.proto.helloP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddRequest_descriptor,
        new java.lang.String[] { "NumOne", "NumTwo", });
    internal_static_AddReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AddReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddReply_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_MultiplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MultiplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultiplyRequest_descriptor,
        new java.lang.String[] { "NumOne", "NumTwo", });
    internal_static_MultiplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_MultiplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultiplyResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
