// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.block.server._generated.proto.hello;

public interface MultiplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MultiplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numOne = 1;</code>
   * @return The numOne.
   */
  int getNumOne();

  /**
   * <code>int32 numTwo = 2;</code>
   * @return The numTwo.
   */
  int getNumTwo();
}
