// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface CreatePostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string writer = 1;</code>
   * @return The writer.
   */
  java.lang.String getWriter();
  /**
   * <code>string writer = 1;</code>
   * @return The bytes for writer.
   */
  com.google.protobuf.ByteString
      getWriterBytes();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>bytes image = 3;</code>
   * @return The image.
   */
  com.google.protobuf.ByteString getImage();

  /**
   * <code>.Location location = 4;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.Location location = 4;</code>
   * @return The location.
   */
  com.block.server._generated.proto.postservice.Location getLocation();
  /**
   * <code>.Location location = 4;</code>
   */
  com.block.server._generated.proto.postservice.LocationOrBuilder getLocationOrBuilder();
}
