// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface CreateCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateCommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string writer = 1;</code>
   * @return The writer.
   */
  java.lang.String getWriter();
  /**
   * <code>string writer = 1;</code>
   * @return The bytes for writer.
   */
  com.google.protobuf.ByteString
      getWriterBytes();

  /**
   * <code>string postId = 2;</code>
   * @return The postId.
   */
  java.lang.String getPostId();
  /**
   * <code>string postId = 2;</code>
   * @return The bytes for postId.
   */
  com.google.protobuf.ByteString
      getPostIdBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
