// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface DeleteCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 commentId = 1;</code>
   * @return The commentId.
   */
  long getCommentId();
}
