// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface DeleteCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commentId = 1;</code>
   * @return The commentId.
   */
  java.lang.String getCommentId();
  /**
   * <code>string commentId = 1;</code>
   * @return The bytes for commentId.
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();
}
