// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface DeletePostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeletePostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The status.
   */
  com.block.server._generated.proto.postservice.PostProtocolStatus getStatus();

  /**
   * <code>string postId = 2;</code>
   * @return The postId.
   */
  java.lang.String getPostId();
  /**
   * <code>string postId = 2;</code>
   * @return The bytes for postId.
   */
  com.google.protobuf.ByteString
      getPostIdBytes();
}
