// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface DistanceFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DistanceFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enabled = 1;</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>int32 distance = 2;</code>
   * @return The distance.
   */
  int getDistance();
}
