// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface GetPostsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPostsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The status.
   */
  com.block.server._generated.proto.postservice.PostProtocolStatus getStatus();

  /**
   * <code>repeated .PostSummary posts = 2;</code>
   */
  java.util.List<com.block.server._generated.proto.postservice.PostSummary> 
      getPostsList();
  /**
   * <code>repeated .PostSummary posts = 2;</code>
   */
  com.block.server._generated.proto.postservice.PostSummary getPosts(int index);
  /**
   * <code>repeated .PostSummary posts = 2;</code>
   */
  int getPostsCount();
  /**
   * <code>repeated .PostSummary posts = 2;</code>
   */
  java.util.List<? extends com.block.server._generated.proto.postservice.PostSummaryOrBuilder> 
      getPostsOrBuilderList();
  /**
   * <code>repeated .PostSummary posts = 2;</code>
   */
  com.block.server._generated.proto.postservice.PostSummaryOrBuilder getPostsOrBuilder(
      int index);
}
