// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

/**
 * Protobuf type {@code GetPostResponse}
 */
public final class GetPostResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetPostResponse)
    GetPostResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPostResponse.newBuilder() to construct.
  private GetPostResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPostResponse() {
    status_ = 0;
    imageUploadUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPostResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPostResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            com.block.server._generated.proto.postservice.PostDto.Builder subBuilder = null;
            if (post_ != null) {
              subBuilder = post_.toBuilder();
            }
            post_ = input.readMessage(com.block.server._generated.proto.postservice.PostDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(post_);
              post_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            imageUploadUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_GetPostResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_GetPostResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.block.server._generated.proto.postservice.GetPostResponse.class, com.block.server._generated.proto.postservice.GetPostResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public com.block.server._generated.proto.postservice.PostProtocolStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.block.server._generated.proto.postservice.PostProtocolStatus result = com.block.server._generated.proto.postservice.PostProtocolStatus.valueOf(status_);
    return result == null ? com.block.server._generated.proto.postservice.PostProtocolStatus.UNRECOGNIZED : result;
  }

  public static final int POST_FIELD_NUMBER = 2;
  private com.block.server._generated.proto.postservice.PostDto post_;
  /**
   * <code>.PostDto post = 2;</code>
   * @return Whether the post field is set.
   */
  @java.lang.Override
  public boolean hasPost() {
    return post_ != null;
  }
  /**
   * <code>.PostDto post = 2;</code>
   * @return The post.
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.PostDto getPost() {
    return post_ == null ? com.block.server._generated.proto.postservice.PostDto.getDefaultInstance() : post_;
  }
  /**
   * <code>.PostDto post = 2;</code>
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.PostDtoOrBuilder getPostOrBuilder() {
    return getPost();
  }

  public static final int IMAGEUPLOADURL_FIELD_NUMBER = 3;
  private volatile java.lang.Object imageUploadUrl_;
  /**
   * <code>string imageUploadUrl = 3;</code>
   * @return The imageUploadUrl.
   */
  @java.lang.Override
  public java.lang.String getImageUploadUrl() {
    java.lang.Object ref = imageUploadUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageUploadUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string imageUploadUrl = 3;</code>
   * @return The bytes for imageUploadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageUploadUrlBytes() {
    java.lang.Object ref = imageUploadUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageUploadUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.block.server._generated.proto.postservice.PostProtocolStatus.SUCCESS.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (post_ != null) {
      output.writeMessage(2, getPost());
    }
    if (!getImageUploadUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageUploadUrl_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.block.server._generated.proto.postservice.PostProtocolStatus.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (post_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPost());
    }
    if (!getImageUploadUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageUploadUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.block.server._generated.proto.postservice.GetPostResponse)) {
      return super.equals(obj);
    }
    com.block.server._generated.proto.postservice.GetPostResponse other = (com.block.server._generated.proto.postservice.GetPostResponse) obj;

    if (status_ != other.status_) return false;
    if (hasPost() != other.hasPost()) return false;
    if (hasPost()) {
      if (!getPost()
          .equals(other.getPost())) return false;
    }
    if (!getImageUploadUrl()
        .equals(other.getImageUploadUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasPost()) {
      hash = (37 * hash) + POST_FIELD_NUMBER;
      hash = (53 * hash) + getPost().hashCode();
    }
    hash = (37 * hash) + IMAGEUPLOADURL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUploadUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.GetPostResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.block.server._generated.proto.postservice.GetPostResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetPostResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetPostResponse)
      com.block.server._generated.proto.postservice.GetPostResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_GetPostResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_GetPostResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.block.server._generated.proto.postservice.GetPostResponse.class, com.block.server._generated.proto.postservice.GetPostResponse.Builder.class);
    }

    // Construct using com.block.server._generated.proto.postservice.GetPostResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (postBuilder_ == null) {
        post_ = null;
      } else {
        post_ = null;
        postBuilder_ = null;
      }
      imageUploadUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_GetPostResponse_descriptor;
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.GetPostResponse getDefaultInstanceForType() {
      return com.block.server._generated.proto.postservice.GetPostResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.GetPostResponse build() {
      com.block.server._generated.proto.postservice.GetPostResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.GetPostResponse buildPartial() {
      com.block.server._generated.proto.postservice.GetPostResponse result = new com.block.server._generated.proto.postservice.GetPostResponse(this);
      result.status_ = status_;
      if (postBuilder_ == null) {
        result.post_ = post_;
      } else {
        result.post_ = postBuilder_.build();
      }
      result.imageUploadUrl_ = imageUploadUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.block.server._generated.proto.postservice.GetPostResponse) {
        return mergeFrom((com.block.server._generated.proto.postservice.GetPostResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.block.server._generated.proto.postservice.GetPostResponse other) {
      if (other == com.block.server._generated.proto.postservice.GetPostResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasPost()) {
        mergePost(other.getPost());
      }
      if (!other.getImageUploadUrl().isEmpty()) {
        imageUploadUrl_ = other.imageUploadUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.block.server._generated.proto.postservice.GetPostResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.block.server._generated.proto.postservice.GetPostResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.PostProtocolStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.PostProtocolStatus status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.PostProtocolStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.block.server._generated.proto.postservice.PostProtocolStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.block.server._generated.proto.postservice.PostProtocolStatus result = com.block.server._generated.proto.postservice.PostProtocolStatus.valueOf(status_);
      return result == null ? com.block.server._generated.proto.postservice.PostProtocolStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.PostProtocolStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.block.server._generated.proto.postservice.PostProtocolStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PostProtocolStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.block.server._generated.proto.postservice.PostDto post_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.PostDto, com.block.server._generated.proto.postservice.PostDto.Builder, com.block.server._generated.proto.postservice.PostDtoOrBuilder> postBuilder_;
    /**
     * <code>.PostDto post = 2;</code>
     * @return Whether the post field is set.
     */
    public boolean hasPost() {
      return postBuilder_ != null || post_ != null;
    }
    /**
     * <code>.PostDto post = 2;</code>
     * @return The post.
     */
    public com.block.server._generated.proto.postservice.PostDto getPost() {
      if (postBuilder_ == null) {
        return post_ == null ? com.block.server._generated.proto.postservice.PostDto.getDefaultInstance() : post_;
      } else {
        return postBuilder_.getMessage();
      }
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public Builder setPost(com.block.server._generated.proto.postservice.PostDto value) {
      if (postBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        post_ = value;
        onChanged();
      } else {
        postBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public Builder setPost(
        com.block.server._generated.proto.postservice.PostDto.Builder builderForValue) {
      if (postBuilder_ == null) {
        post_ = builderForValue.build();
        onChanged();
      } else {
        postBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public Builder mergePost(com.block.server._generated.proto.postservice.PostDto value) {
      if (postBuilder_ == null) {
        if (post_ != null) {
          post_ =
            com.block.server._generated.proto.postservice.PostDto.newBuilder(post_).mergeFrom(value).buildPartial();
        } else {
          post_ = value;
        }
        onChanged();
      } else {
        postBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public Builder clearPost() {
      if (postBuilder_ == null) {
        post_ = null;
        onChanged();
      } else {
        post_ = null;
        postBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public com.block.server._generated.proto.postservice.PostDto.Builder getPostBuilder() {
      
      onChanged();
      return getPostFieldBuilder().getBuilder();
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    public com.block.server._generated.proto.postservice.PostDtoOrBuilder getPostOrBuilder() {
      if (postBuilder_ != null) {
        return postBuilder_.getMessageOrBuilder();
      } else {
        return post_ == null ?
            com.block.server._generated.proto.postservice.PostDto.getDefaultInstance() : post_;
      }
    }
    /**
     * <code>.PostDto post = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.PostDto, com.block.server._generated.proto.postservice.PostDto.Builder, com.block.server._generated.proto.postservice.PostDtoOrBuilder> 
        getPostFieldBuilder() {
      if (postBuilder_ == null) {
        postBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.block.server._generated.proto.postservice.PostDto, com.block.server._generated.proto.postservice.PostDto.Builder, com.block.server._generated.proto.postservice.PostDtoOrBuilder>(
                getPost(),
                getParentForChildren(),
                isClean());
        post_ = null;
      }
      return postBuilder_;
    }

    private java.lang.Object imageUploadUrl_ = "";
    /**
     * <code>string imageUploadUrl = 3;</code>
     * @return The imageUploadUrl.
     */
    public java.lang.String getImageUploadUrl() {
      java.lang.Object ref = imageUploadUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUploadUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageUploadUrl = 3;</code>
     * @return The bytes for imageUploadUrl.
     */
    public com.google.protobuf.ByteString
        getImageUploadUrlBytes() {
      java.lang.Object ref = imageUploadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUploadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageUploadUrl = 3;</code>
     * @param value The imageUploadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUploadUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageUploadUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageUploadUrl = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageUploadUrl() {
      
      imageUploadUrl_ = getDefaultInstance().getImageUploadUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string imageUploadUrl = 3;</code>
     * @param value The bytes for imageUploadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUploadUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageUploadUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetPostResponse)
  }

  // @@protoc_insertion_point(class_scope:GetPostResponse)
  private static final com.block.server._generated.proto.postservice.GetPostResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.block.server._generated.proto.postservice.GetPostResponse();
  }

  public static com.block.server._generated.proto.postservice.GetPostResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPostResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPostResponse>() {
    @java.lang.Override
    public GetPostResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPostResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPostResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPostResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.block.server._generated.proto.postservice.GetPostResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

