// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface LocationDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocationDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double lat = 1;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double long = 2;</code>
   * @return The long.
   */
  double getLong();
}
