// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface ModifyCommentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModifyCommentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.PostProtocolStatus status = 1;</code>
   * @return The status.
   */
  com.block.server._generated.proto.postservice.PostProtocolStatus getStatus();

  /**
   * <code>string commentId = 2;</code>
   * @return The commentId.
   */
  java.lang.String getCommentId();
  /**
   * <code>string commentId = 2;</code>
   * @return The bytes for commentId.
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();
}
