// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

/**
 * Protobuf type {@code PostDto}
 */
public final class PostDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PostDto)
    PostDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PostDto.newBuilder() to construct.
  private PostDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PostDto() {
    content_ = "";
    imageUrl_ = "";
    comments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PostDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PostDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            postId_ = input.readInt64();
            break;
          }
          case 18: {
            com.block.server._generated.proto.postservice.UserDto.Builder subBuilder = null;
            if (author_ != null) {
              subBuilder = author_.toBuilder();
            }
            author_ = input.readMessage(com.block.server._generated.proto.postservice.UserDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(author_);
              author_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            imageUrl_ = s;
            break;
          }
          case 40: {

            likes_ = input.readInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              comments_ = new java.util.ArrayList<com.block.server._generated.proto.postservice.CommentDto>();
              mutable_bitField0_ |= 0x00000001;
            }
            comments_.add(
                input.readMessage(com.block.server._generated.proto.postservice.CommentDto.parser(), extensionRegistry));
            break;
          }
          case 58: {
            com.block.server._generated.proto.postservice.LocationDto.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(com.block.server._generated.proto.postservice.LocationDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        comments_ = java.util.Collections.unmodifiableList(comments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_PostDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_PostDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.block.server._generated.proto.postservice.PostDto.class, com.block.server._generated.proto.postservice.PostDto.Builder.class);
  }

  public static final int POSTID_FIELD_NUMBER = 1;
  private long postId_;
  /**
   * <code>int64 postId = 1;</code>
   * @return The postId.
   */
  @java.lang.Override
  public long getPostId() {
    return postId_;
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  private com.block.server._generated.proto.postservice.UserDto author_;
  /**
   * <code>.UserDto author = 2;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return author_ != null;
  }
  /**
   * <code>.UserDto author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.UserDto getAuthor() {
    return author_ == null ? com.block.server._generated.proto.postservice.UserDto.getDefaultInstance() : author_;
  }
  /**
   * <code>.UserDto author = 2;</code>
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.UserDtoOrBuilder getAuthorOrBuilder() {
    return getAuthor();
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object imageUrl_;
  /**
   * <code>string imageUrl = 4;</code>
   * @return The imageUrl.
   */
  @java.lang.Override
  public java.lang.String getImageUrl() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string imageUrl = 4;</code>
   * @return The bytes for imageUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIKES_FIELD_NUMBER = 5;
  private int likes_;
  /**
   * <code>int32 likes = 5;</code>
   * @return The likes.
   */
  @java.lang.Override
  public int getLikes() {
    return likes_;
  }

  public static final int COMMENTS_FIELD_NUMBER = 6;
  private java.util.List<com.block.server._generated.proto.postservice.CommentDto> comments_;
  /**
   * <code>repeated .CommentDto comments = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.block.server._generated.proto.postservice.CommentDto> getCommentsList() {
    return comments_;
  }
  /**
   * <code>repeated .CommentDto comments = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.block.server._generated.proto.postservice.CommentDtoOrBuilder> 
      getCommentsOrBuilderList() {
    return comments_;
  }
  /**
   * <code>repeated .CommentDto comments = 6;</code>
   */
  @java.lang.Override
  public int getCommentsCount() {
    return comments_.size();
  }
  /**
   * <code>repeated .CommentDto comments = 6;</code>
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.CommentDto getComments(int index) {
    return comments_.get(index);
  }
  /**
   * <code>repeated .CommentDto comments = 6;</code>
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.CommentDtoOrBuilder getCommentsOrBuilder(
      int index) {
    return comments_.get(index);
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  private com.block.server._generated.proto.postservice.LocationDto location_;
  /**
   * <code>.LocationDto location = 7;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.LocationDto location = 7;</code>
   * @return The location.
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.LocationDto getLocation() {
    return location_ == null ? com.block.server._generated.proto.postservice.LocationDto.getDefaultInstance() : location_;
  }
  /**
   * <code>.LocationDto location = 7;</code>
   */
  @java.lang.Override
  public com.block.server._generated.proto.postservice.LocationDtoOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (postId_ != 0L) {
      output.writeInt64(1, postId_);
    }
    if (author_ != null) {
      output.writeMessage(2, getAuthor());
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageUrl_);
    }
    if (likes_ != 0) {
      output.writeInt32(5, likes_);
    }
    for (int i = 0; i < comments_.size(); i++) {
      output.writeMessage(6, comments_.get(i));
    }
    if (location_ != null) {
      output.writeMessage(7, getLocation());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (postId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, postId_);
    }
    if (author_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthor());
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageUrl_);
    }
    if (likes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, likes_);
    }
    for (int i = 0; i < comments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, comments_.get(i));
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLocation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.block.server._generated.proto.postservice.PostDto)) {
      return super.equals(obj);
    }
    com.block.server._generated.proto.postservice.PostDto other = (com.block.server._generated.proto.postservice.PostDto) obj;

    if (getPostId()
        != other.getPostId()) return false;
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getImageUrl()
        .equals(other.getImageUrl())) return false;
    if (getLikes()
        != other.getLikes()) return false;
    if (!getCommentsList()
        .equals(other.getCommentsList())) return false;
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPostId());
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + IMAGEURL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUrl().hashCode();
    hash = (37 * hash) + LIKES_FIELD_NUMBER;
    hash = (53 * hash) + getLikes();
    if (getCommentsCount() > 0) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getCommentsList().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.block.server._generated.proto.postservice.PostDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.block.server._generated.proto.postservice.PostDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PostDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PostDto)
      com.block.server._generated.proto.postservice.PostDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_PostDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_PostDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.block.server._generated.proto.postservice.PostDto.class, com.block.server._generated.proto.postservice.PostDto.Builder.class);
    }

    // Construct using com.block.server._generated.proto.postservice.PostDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      postId_ = 0L;

      if (authorBuilder_ == null) {
        author_ = null;
      } else {
        author_ = null;
        authorBuilder_ = null;
      }
      content_ = "";

      imageUrl_ = "";

      likes_ = 0;

      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        commentsBuilder_.clear();
      }
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.block.server._generated.proto.postservice.PostProtocolOuterClass.internal_static_PostDto_descriptor;
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.PostDto getDefaultInstanceForType() {
      return com.block.server._generated.proto.postservice.PostDto.getDefaultInstance();
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.PostDto build() {
      com.block.server._generated.proto.postservice.PostDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.block.server._generated.proto.postservice.PostDto buildPartial() {
      com.block.server._generated.proto.postservice.PostDto result = new com.block.server._generated.proto.postservice.PostDto(this);
      int from_bitField0_ = bitField0_;
      result.postId_ = postId_;
      if (authorBuilder_ == null) {
        result.author_ = author_;
      } else {
        result.author_ = authorBuilder_.build();
      }
      result.content_ = content_;
      result.imageUrl_ = imageUrl_;
      result.likes_ = likes_;
      if (commentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          comments_ = java.util.Collections.unmodifiableList(comments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.comments_ = comments_;
      } else {
        result.comments_ = commentsBuilder_.build();
      }
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.block.server._generated.proto.postservice.PostDto) {
        return mergeFrom((com.block.server._generated.proto.postservice.PostDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.block.server._generated.proto.postservice.PostDto other) {
      if (other == com.block.server._generated.proto.postservice.PostDto.getDefaultInstance()) return this;
      if (other.getPostId() != 0L) {
        setPostId(other.getPostId());
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getImageUrl().isEmpty()) {
        imageUrl_ = other.imageUrl_;
        onChanged();
      }
      if (other.getLikes() != 0) {
        setLikes(other.getLikes());
      }
      if (commentsBuilder_ == null) {
        if (!other.comments_.isEmpty()) {
          if (comments_.isEmpty()) {
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommentsIsMutable();
            comments_.addAll(other.comments_);
          }
          onChanged();
        }
      } else {
        if (!other.comments_.isEmpty()) {
          if (commentsBuilder_.isEmpty()) {
            commentsBuilder_.dispose();
            commentsBuilder_ = null;
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            commentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommentsFieldBuilder() : null;
          } else {
            commentsBuilder_.addAllMessages(other.comments_);
          }
        }
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.block.server._generated.proto.postservice.PostDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.block.server._generated.proto.postservice.PostDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long postId_ ;
    /**
     * <code>int64 postId = 1;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }
    /**
     * <code>int64 postId = 1;</code>
     * @param value The postId to set.
     * @return This builder for chaining.
     */
    public Builder setPostId(long value) {
      
      postId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 postId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostId() {
      
      postId_ = 0L;
      onChanged();
      return this;
    }

    private com.block.server._generated.proto.postservice.UserDto author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.UserDto, com.block.server._generated.proto.postservice.UserDto.Builder, com.block.server._generated.proto.postservice.UserDtoOrBuilder> authorBuilder_;
    /**
     * <code>.UserDto author = 2;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return authorBuilder_ != null || author_ != null;
    }
    /**
     * <code>.UserDto author = 2;</code>
     * @return The author.
     */
    public com.block.server._generated.proto.postservice.UserDto getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? com.block.server._generated.proto.postservice.UserDto.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public Builder setAuthor(com.block.server._generated.proto.postservice.UserDto value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
        onChanged();
      } else {
        authorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public Builder setAuthor(
        com.block.server._generated.proto.postservice.UserDto.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
        onChanged();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public Builder mergeAuthor(com.block.server._generated.proto.postservice.UserDto value) {
      if (authorBuilder_ == null) {
        if (author_ != null) {
          author_ =
            com.block.server._generated.proto.postservice.UserDto.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }
        onChanged();
      } else {
        authorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public Builder clearAuthor() {
      if (authorBuilder_ == null) {
        author_ = null;
        onChanged();
      } else {
        author_ = null;
        authorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public com.block.server._generated.proto.postservice.UserDto.Builder getAuthorBuilder() {
      
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    public com.block.server._generated.proto.postservice.UserDtoOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            com.block.server._generated.proto.postservice.UserDto.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>.UserDto author = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.UserDto, com.block.server._generated.proto.postservice.UserDto.Builder, com.block.server._generated.proto.postservice.UserDtoOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.block.server._generated.proto.postservice.UserDto, com.block.server._generated.proto.postservice.UserDto.Builder, com.block.server._generated.proto.postservice.UserDtoOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imageUrl_ = "";
    /**
     * <code>string imageUrl = 4;</code>
     * @return The imageUrl.
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageUrl = 4;</code>
     * @return The bytes for imageUrl.
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageUrl = 4;</code>
     * @param value The imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageUrl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageUrl() {
      
      imageUrl_ = getDefaultInstance().getImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string imageUrl = 4;</code>
     * @param value The bytes for imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageUrl_ = value;
      onChanged();
      return this;
    }

    private int likes_ ;
    /**
     * <code>int32 likes = 5;</code>
     * @return The likes.
     */
    @java.lang.Override
    public int getLikes() {
      return likes_;
    }
    /**
     * <code>int32 likes = 5;</code>
     * @param value The likes to set.
     * @return This builder for chaining.
     */
    public Builder setLikes(int value) {
      
      likes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 likes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLikes() {
      
      likes_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.block.server._generated.proto.postservice.CommentDto> comments_ =
      java.util.Collections.emptyList();
    private void ensureCommentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        comments_ = new java.util.ArrayList<com.block.server._generated.proto.postservice.CommentDto>(comments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.block.server._generated.proto.postservice.CommentDto, com.block.server._generated.proto.postservice.CommentDto.Builder, com.block.server._generated.proto.postservice.CommentDtoOrBuilder> commentsBuilder_;

    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public java.util.List<com.block.server._generated.proto.postservice.CommentDto> getCommentsList() {
      if (commentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(comments_);
      } else {
        return commentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public int getCommentsCount() {
      if (commentsBuilder_ == null) {
        return comments_.size();
      } else {
        return commentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public com.block.server._generated.proto.postservice.CommentDto getComments(int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);
      } else {
        return commentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder setComments(
        int index, com.block.server._generated.proto.postservice.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.set(index, value);
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder setComments(
        int index, com.block.server._generated.proto.postservice.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.set(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder addComments(com.block.server._generated.proto.postservice.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder addComments(
        int index, com.block.server._generated.proto.postservice.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(index, value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder addComments(
        com.block.server._generated.proto.postservice.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder addComments(
        int index, com.block.server._generated.proto.postservice.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder addAllComments(
        java.lang.Iterable<? extends com.block.server._generated.proto.postservice.CommentDto> values) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, comments_);
        onChanged();
      } else {
        commentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder clearComments() {
      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        commentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public Builder removeComments(int index) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.remove(index);
        onChanged();
      } else {
        commentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public com.block.server._generated.proto.postservice.CommentDto.Builder getCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public com.block.server._generated.proto.postservice.CommentDtoOrBuilder getCommentsOrBuilder(
        int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);  } else {
        return commentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public java.util.List<? extends com.block.server._generated.proto.postservice.CommentDtoOrBuilder> 
         getCommentsOrBuilderList() {
      if (commentsBuilder_ != null) {
        return commentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(comments_);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public com.block.server._generated.proto.postservice.CommentDto.Builder addCommentsBuilder() {
      return getCommentsFieldBuilder().addBuilder(
          com.block.server._generated.proto.postservice.CommentDto.getDefaultInstance());
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public com.block.server._generated.proto.postservice.CommentDto.Builder addCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().addBuilder(
          index, com.block.server._generated.proto.postservice.CommentDto.getDefaultInstance());
    }
    /**
     * <code>repeated .CommentDto comments = 6;</code>
     */
    public java.util.List<com.block.server._generated.proto.postservice.CommentDto.Builder> 
         getCommentsBuilderList() {
      return getCommentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.block.server._generated.proto.postservice.CommentDto, com.block.server._generated.proto.postservice.CommentDto.Builder, com.block.server._generated.proto.postservice.CommentDtoOrBuilder> 
        getCommentsFieldBuilder() {
      if (commentsBuilder_ == null) {
        commentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.block.server._generated.proto.postservice.CommentDto, com.block.server._generated.proto.postservice.CommentDto.Builder, com.block.server._generated.proto.postservice.CommentDtoOrBuilder>(
                comments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        comments_ = null;
      }
      return commentsBuilder_;
    }

    private com.block.server._generated.proto.postservice.LocationDto location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.LocationDto, com.block.server._generated.proto.postservice.LocationDto.Builder, com.block.server._generated.proto.postservice.LocationDtoOrBuilder> locationBuilder_;
    /**
     * <code>.LocationDto location = 7;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.LocationDto location = 7;</code>
     * @return The location.
     */
    public com.block.server._generated.proto.postservice.LocationDto getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? com.block.server._generated.proto.postservice.LocationDto.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public Builder setLocation(com.block.server._generated.proto.postservice.LocationDto value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public Builder setLocation(
        com.block.server._generated.proto.postservice.LocationDto.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public Builder mergeLocation(com.block.server._generated.proto.postservice.LocationDto value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            com.block.server._generated.proto.postservice.LocationDto.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public com.block.server._generated.proto.postservice.LocationDto.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    public com.block.server._generated.proto.postservice.LocationDtoOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            com.block.server._generated.proto.postservice.LocationDto.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.LocationDto location = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.block.server._generated.proto.postservice.LocationDto, com.block.server._generated.proto.postservice.LocationDto.Builder, com.block.server._generated.proto.postservice.LocationDtoOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.block.server._generated.proto.postservice.LocationDto, com.block.server._generated.proto.postservice.LocationDto.Builder, com.block.server._generated.proto.postservice.LocationDtoOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PostDto)
  }

  // @@protoc_insertion_point(class_scope:PostDto)
  private static final com.block.server._generated.proto.postservice.PostDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.block.server._generated.proto.postservice.PostDto();
  }

  public static com.block.server._generated.proto.postservice.PostDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostDto>
      PARSER = new com.google.protobuf.AbstractParser<PostDto>() {
    @java.lang.Override
    public PostDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PostDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PostDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PostDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.block.server._generated.proto.postservice.PostDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

