// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public final class PostProtocolOuterClass {
  private PostProtocolOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostsRequest_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostsRequest_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostsRequest_Filter_DistanceFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostsRequest_Filter_DistanceFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPostsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPostsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyPostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyPostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCommentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCommentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyCommentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyCommentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteCommentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteCommentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LikePostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LikePostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LikePostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LikePostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadImageResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadImageResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadImageResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadImageResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PostProtocol.proto\032\037google/protobuf/ti" +
      "mestamp.proto\"(\n\013LocationDto\022\013\n\003lat\030\001 \001(" +
      "\001\022\014\n\004long\030\002 \001(\001\"g\n\nCommentDto\022\021\n\tcomment" +
      "Id\030\001 \001(\t\022\016\n\006author\030\002 \001(\t\022\017\n\007content\030\003 \001(" +
      "\t\022\021\n\tcreatedTS\030\004 \001(\005\022\022\n\nmodifiedTS\030\005 \001(\005" +
      "\"/\n\007UserDto\022\020\n\010nickname\030\001 \001(\t\022\022\n\nprofile" +
      "Url\030\002 \001(\t\"\327\001\n\007PostDto\022\016\n\006postId\030\001 \001(\003\022\030\n" +
      "\006author\030\002 \001(\0132\010.UserDto\022\017\n\007content\030\003 \001(\t" +
      "\022\020\n\010imageUrl\030\004 \001(\t\022\r\n\005likes\030\005 \001(\005\022\035\n\010com" +
      "ments\030\006 \003(\0132\013.CommentDto\022\036\n\010location\030\007 \001" +
      "(\0132\014.LocationDto\0221\n\rremainingTime\030\010 \001(\0132" +
      "\032.google.protobuf.Timestamp\" \n\016GetPostRe" +
      "quest\022\016\n\006postId\030\001 \001(\003\"f\n\017GetPostResponse" +
      "\022#\n\006status\030\001 \001(\0162\023.PostProtocolStatus\022\026\n" +
      "\004post\030\002 \001(\0132\010.PostDto\022\026\n\016imageUploadUrl\030" +
      "\003 \001(\t\"\273\002\n\017GetPostsRequest\022\022\n\npageNumber\030" +
      "\001 \001(\005\022\032\n\rresultPerPage\030\002 \001(\005H\000\210\001\001\022%\n\017cur" +
      "rentLocation\030\003 \001(\0132\014.LocationDto\022\'\n\006filt" +
      "er\030\004 \001(\0132\027.GetPostsRequest.Filter\032\225\001\n\006Fi" +
      "lter\022>\n\016distanceFilter\030\001 \001(\0132&.GetPostsR" +
      "equest.Filter.DistanceFilter\022\026\n\016rightNow" +
      "Filter\030\002 \001(\010\0323\n\016DistanceFilter\022\017\n\007enable" +
      "d\030\001 \001(\010\022\020\n\010distance\030\002 \001(\005B\020\n\016_resultPerP" +
      "age\"P\n\020GetPostsResponse\022#\n\006status\030\001 \001(\0162" +
      "\023.PostProtocolStatus\022\027\n\005posts\030\002 \003(\0132\010.Po" +
      "stDto\"T\n\021CreatePostRequest\022\016\n\006author\030\001 \001" +
      "(\t\022\017\n\007content\030\002 \001(\t\022\036\n\010location\030\003 \001(\0132\014." +
      "LocationDto\"a\n\022CreatePostResponse\022#\n\006sta" +
      "tus\030\001 \001(\0162\023.PostProtocolStatus\022\016\n\006postId" +
      "\030\002 \001(\003\022\026\n\016uploadImageUrl\030\003 \001(\t\"K\n\021Modify" +
      "PostRequest\022\016\n\006postId\030\001 \001(\003\022\017\n\007content\030\002" +
      " \001(\t\022\025\n\rmodifiedImage\030\003 \001(\010\"a\n\022ModifyPos" +
      "tResponse\022#\n\006status\030\001 \001(\0162\023.PostProtocol" +
      "Status\022\016\n\006postId\030\002 \001(\003\022\026\n\016uploadImageUrl" +
      "\030\003 \001(\t\"#\n\021DeletePostRequest\022\016\n\006postId\030\001 " +
      "\001(\003\"I\n\022DeletePostResponse\022#\n\006status\030\001 \001(" +
      "\0162\023.PostProtocolStatus\022\016\n\006postId\030\002 \001(\003\"G" +
      "\n\024CreateCommentRequest\022\016\n\006author\030\001 \001(\t\022\016" +
      "\n\006postId\030\002 \001(\003\022\017\n\007content\030\003 \001(\t\"O\n\025Creat" +
      "eCommentResponse\022#\n\006status\030\001 \001(\0162\023.PostP" +
      "rotocolStatus\022\021\n\tcommentId\030\002 \001(\003\":\n\024Modi" +
      "fyCommentRequest\022\021\n\tcommentId\030\001 \001(\003\022\017\n\007c" +
      "ontent\030\002 \001(\t\"O\n\025ModifyCommentResponse\022#\n" +
      "\006status\030\001 \001(\0162\023.PostProtocolStatus\022\021\n\tco" +
      "mmentId\030\002 \001(\003\")\n\024DeleteCommentRequest\022\021\n" +
      "\tcommentId\030\001 \001(\003\"<\n\025DeleteCommentRespons" +
      "e\022#\n\006status\030\001 \001(\0162\023.PostProtocolStatus\"/" +
      "\n\017LikePostRequest\022\016\n\006postId\030\001 \001(\003\022\014\n\004lik" +
      "e\030\002 \001(\010\"O\n\020LikePostResponse\022#\n\006status\030\001 " +
      "\001(\0162\023.PostProtocolStatus\022\026\n\004post\030\002 \001(\0132\010" +
      ".PostDto\";\n\030UploadImageResultRequest\022\016\n\006" +
      "postId\030\001 \001(\003\022\017\n\007success\030\002 \001(\010\"P\n\031UploadI" +
      "mageResultResponse\022#\n\006status\030\001 \001(\0162\023.Pos" +
      "tProtocolStatus\022\016\n\006postId\030\002 \001(\003*f\n\022PostP" +
      "rotocolStatus\022\013\n\007SUCCESS\020\000\022\013\n\007NO_POST\020\001\022" +
      "\016\n\nNO_COMMENT\020\002\022\022\n\016NOT_AUTHORIZED\020\003\022\022\n\016I" +
      "NTERNAL_ERROR\020c2\234\005\n\014PostProtocol\022.\n\007GetP" +
      "ost\022\017.GetPostRequest\032\020.GetPostResponse\"\000" +
      "\0221\n\010GetPosts\022\020.GetPostsRequest\032\021.GetPost" +
      "sResponse\"\000\0227\n\nCreatePost\022\022.CreatePostRe" +
      "quest\032\023.CreatePostResponse\"\000\0227\n\nModifyPo" +
      "st\022\022.ModifyPostRequest\032\023.ModifyPostRespo" +
      "nse\"\000\0227\n\nDeletePost\022\022.DeletePostRequest\032" +
      "\023.DeletePostResponse\"\000\022@\n\rCreateComment\022" +
      "\025.CreateCommentRequest\032\026.CreateCommentRe" +
      "sponse\"\000\022@\n\rModifyComment\022\025.ModifyCommen" +
      "tRequest\032\026.ModifyCommentResponse\"\000\022@\n\rDe" +
      "leteComment\022\025.DeleteCommentRequest\032\026.Del" +
      "eteCommentResponse\"\000\0221\n\010LikePost\022\020.LikeP" +
      "ostRequest\032\021.LikePostResponse\"\000\0227\n\016Cance" +
      "lLikePost\022\020.LikePostRequest\032\021.LikePostRe" +
      "sponse\"\000\022L\n\021UploadImageResult\022\031.UploadIm" +
      "ageResultRequest\032\032.UploadImageResultResp" +
      "onse\"\000B1\n-com.block.server._generated.pr" +
      "oto.postserviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_LocationDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocationDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationDto_descriptor,
        new java.lang.String[] { "Lat", "Long", });
    internal_static_CommentDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CommentDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentDto_descriptor,
        new java.lang.String[] { "CommentId", "Author", "Content", "CreatedTS", "ModifiedTS", });
    internal_static_UserDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserDto_descriptor,
        new java.lang.String[] { "Nickname", "ProfileUrl", });
    internal_static_PostDto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PostDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostDto_descriptor,
        new java.lang.String[] { "PostId", "Author", "Content", "ImageUrl", "Likes", "Comments", "Location", "RemainingTime", });
    internal_static_GetPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostRequest_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_GetPostResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetPostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostResponse_descriptor,
        new java.lang.String[] { "Status", "Post", "ImageUploadUrl", });
    internal_static_GetPostsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetPostsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostsRequest_descriptor,
        new java.lang.String[] { "PageNumber", "ResultPerPage", "CurrentLocation", "Filter", "ResultPerPage", });
    internal_static_GetPostsRequest_Filter_descriptor =
      internal_static_GetPostsRequest_descriptor.getNestedTypes().get(0);
    internal_static_GetPostsRequest_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostsRequest_Filter_descriptor,
        new java.lang.String[] { "DistanceFilter", "RightNowFilter", });
    internal_static_GetPostsRequest_Filter_DistanceFilter_descriptor =
      internal_static_GetPostsRequest_Filter_descriptor.getNestedTypes().get(0);
    internal_static_GetPostsRequest_Filter_DistanceFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostsRequest_Filter_DistanceFilter_descriptor,
        new java.lang.String[] { "Enabled", "Distance", });
    internal_static_GetPostsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetPostsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPostsResponse_descriptor,
        new java.lang.String[] { "Status", "Posts", });
    internal_static_CreatePostRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreatePostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePostRequest_descriptor,
        new java.lang.String[] { "Author", "Content", "Location", });
    internal_static_CreatePostResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CreatePostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePostResponse_descriptor,
        new java.lang.String[] { "Status", "PostId", "UploadImageUrl", });
    internal_static_ModifyPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ModifyPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyPostRequest_descriptor,
        new java.lang.String[] { "PostId", "Content", "ModifiedImage", });
    internal_static_ModifyPostResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ModifyPostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyPostResponse_descriptor,
        new java.lang.String[] { "Status", "PostId", "UploadImageUrl", });
    internal_static_DeletePostRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_DeletePostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePostRequest_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_DeletePostResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DeletePostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePostResponse_descriptor,
        new java.lang.String[] { "Status", "PostId", });
    internal_static_CreateCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CreateCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCommentRequest_descriptor,
        new java.lang.String[] { "Author", "PostId", "Content", });
    internal_static_CreateCommentResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_CreateCommentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCommentResponse_descriptor,
        new java.lang.String[] { "Status", "CommentId", });
    internal_static_ModifyCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ModifyCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyCommentRequest_descriptor,
        new java.lang.String[] { "CommentId", "Content", });
    internal_static_ModifyCommentResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ModifyCommentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyCommentResponse_descriptor,
        new java.lang.String[] { "Status", "CommentId", });
    internal_static_DeleteCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_DeleteCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteCommentRequest_descriptor,
        new java.lang.String[] { "CommentId", });
    internal_static_DeleteCommentResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_DeleteCommentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteCommentResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_LikePostRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_LikePostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LikePostRequest_descriptor,
        new java.lang.String[] { "PostId", "Like", });
    internal_static_LikePostResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_LikePostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LikePostResponse_descriptor,
        new java.lang.String[] { "Status", "Post", });
    internal_static_UploadImageResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_UploadImageResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadImageResultRequest_descriptor,
        new java.lang.String[] { "PostId", "Success", });
    internal_static_UploadImageResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_UploadImageResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadImageResultResponse_descriptor,
        new java.lang.String[] { "Status", "PostId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
