// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostProtocol.proto

package com.block.server._generated.proto.postservice;

public interface PostSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 postId = 1;</code>
   * @return The postId.
   */
  long getPostId();

  /**
   * <code>.LocationDto location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.LocationDto location = 2;</code>
   * @return The location.
   */
  com.block.server._generated.proto.postservice.LocationDto getLocation();
  /**
   * <code>.LocationDto location = 2;</code>
   */
  com.block.server._generated.proto.postservice.LocationDtoOrBuilder getLocationOrBuilder();
}
