// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProtocol.proto

package com.block.server._generated.proto.userservice;

public interface SignInResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignInResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SignInResponse.SignInStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.SignInResponse.SignInStatus status = 1;</code>
   * @return The status.
   */
  com.block.server._generated.proto.userservice.SignInResponse.SignInStatus getStatus();

  /**
   * <code>string nickname = 2;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 2;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string avatarId = 3;</code>
   * @return The avatarId.
   */
  java.lang.String getAvatarId();
  /**
   * <code>string avatarId = 3;</code>
   * @return The bytes for avatarId.
   */
  com.google.protobuf.ByteString
      getAvatarIdBytes();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
