// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProtocol.proto

package com.block.server._generated.proto.userservice;

public interface SignUpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignUpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string nickname = 3;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 3;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>.SignUpRequest.Gender gender = 4;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.SignUpRequest.Gender gender = 4;</code>
   * @return The gender.
   */
  com.block.server._generated.proto.userservice.SignUpRequest.Gender getGender();

  /**
   * <code>string avatar = 5;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 5;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>string birthday = 6;</code>
   * @return The birthday.
   */
  java.lang.String getBirthday();
  /**
   * <code>string birthday = 6;</code>
   * @return The bytes for birthday.
   */
  com.google.protobuf.ByteString
      getBirthdayBytes();
}
