// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.block.server._generated.proto.userservice;

public interface SignUpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignUpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SignUpResponse.SignUpStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.SignUpResponse.SignUpStatus status = 1;</code>
   * @return The status.
   */
  com.block.server._generated.proto.userservice.SignUpResponse.SignUpStatus getStatus();

  /**
   * <code>string nickname = 2;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 2;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string profileUrl = 3;</code>
   * @return The profileUrl.
   */
  java.lang.String getProfileUrl();
  /**
   * <code>string profileUrl = 3;</code>
   * @return The bytes for profileUrl.
   */
  com.google.protobuf.ByteString
      getProfileUrlBytes();
}
