export enum ActionType {
  USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR",

  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR = 'USER_LOGIN_ERROR',
}
