export enum ActionType {
  USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR',

  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR = 'USER_LOGIN_ERROR',

  GET_USER_LOCATION_REQUEST = 'GET_USER_LOCATION_REQUEST',
  GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS',
  GET_USER_LOCATION_ERROR = 'GET_USER_LOCATION_ERROR',

  ADD_POST_REQUEST = 'ADD_POST_REQUEST',
  ADD_POST_SUCCESS = 'ADD_POST_SUCCESS',
  ADD_POST_ERROR = 'ADD_POST_ERROR',

  CAPTURE_IMAGE_REQUEST = 'CAPTURE_IMAGE_REQUEST',
  CAPTURE_IMAGE_SUCCESS = 'CAPTURE_IMAGE_SUCCESS',
  CAPTURE_IMAGE_ERROR = 'CAPTURE_IMAGE_ERROR',

  SAVE_TEMP_POST = 'SAVE_TEMP_POST',
  REMOVE_TEMP_POST = 'REMOVE_TEMP_POST',
}
