version: '3'

services:
  envoy-proxy:
    image: envoyproxy/envoy:v1.17.0
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - ${ENVOY_ORIGIN_CONFIG_PATH}:/etc/envoy/envoy.yaml
    restart: always
    networks:
      - backend
  server:
    image: ${SERVER_IMAGE}:${SERVER_IMAGE_TAG}
    environment: 
      - CONTAINER_INTERNAL_CONFIG_PATH=$CONTAINER_INTERNAL_CONFIG_PATH
      - PROFILE=$INFRA
    ports:
      - "8080:8080"
      - "6565:6565"
    networks:
      - backend
    volumes:
      - "${CONFIG_ORIGIN_PATH}:${CONTAINER_INTERNAL_CONFIG_DIR}"

networks:
  backend:
    name: backend_internal