version: '3'

services:
  envoy-proxy:
    image: envoyproxy/envoy:v1.17.0
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - $ENVOY_ORIGIN_CONFIG_PATH:/etc/envoy/envoy.yaml
    restart: always